name = "SpatioTemporalTraits"
uuid = "6a04ffb7-1155-443c-92eb-f1f26f00354c"
authors = ["Zachary P. Christensen <zchristensen7@gmail.com>"]
version = "0.1.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
